name: GringoPost Bot Advanced

on:
  schedule:
    # Lunes, miércoles y viernes a las 14:00 UTC (9am GMT-5)
    - cron: '0 14 * * 1,3,5'
  workflow_dispatch:
    # Permite ejecución manual con estos inputs
    inputs:
      headless:
        description: 'Run in headless mode?'
        required: true
        default: 'false'
      title:
        description: 'Post title'
        required: true
      description:
        description: 'Post description'
        required: true
      contact:
        description: 'Public contact email/info'
        required: true
      city:
        description: 'City for the post'
        required: true

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run Advanced GringoPost Bot
        env:
          GRINGO_EMAIL: ${{ secrets.GRINGO_EMAIL }}
          GRINGO_PASSWORD: ${{ secrets.GRINGO_PASSWORD }}
        run: |
          echo "▶️ Ejecutando bot avanzado de GringoPost..."
          python gringopost_advanced.py \
            --headless=${{ github.event.inputs.headless }} \
            --title="${{ github.event.inputs.title }}" \
            --description="${{ github.event.inputs.description }}" \
            --contact="${{ github.event.inputs.contact }}" \
            --city="${{ github.event.inputs.city }}"
