name: GringoPost Bot Advanced

on:
  schedule:
    - cron: '0 14 * * 1,3,5'  # Lunes, miércoles, viernes a las 14:00 UTC (9am GMT-5)
  workflow_dispatch:  # Permite ejecución manual

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install chromium

    - name: Run Advanced GringoPost Bot
      env:
        GRINGO_EMAIL: ${{ secrets.GRINGO_EMAIL }}
        GRINGO_PASSWORD: ${{ secrets.GRINGO_PASSWORD }}
      run: |
        echo "▶️ Ejecutando bot avanzado de GringoPost..."
        python gringopost_advanced.py --headless
