name: GringoPost Bot

on:
  schedule:
    - cron: '0 14 * * 1,3' # Runs at 9am GMT-5 (Ecuador) every Monday and Wednesday
  workflow_dispatch: # Allows manual run

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      - name: Run posting bot
        env:
          GRINGO_EMAIL: ${{ secrets.GRINGO_EMAIL }}
          GRINGO_PASSWORD: ${{ secrets.GRINGO_PASSWORD }}
        run: |
          python post_gringopost.py
